///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("5ab547af-466f-490f-9902-0cb3ae7817f1", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test_1Repository repository.
        /// </summary>
        public static Test_1Repository repo = Test_1Repository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.GoogleChrome' at 20;15.", repo.Explorer.GoogleChromeInfo, new RecordItemIndex(0));
            repo.Explorer.GoogleChrome.Click("20;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoogleGoogleChrome.PasekAdresuIWyszukiwania' at 434;10.", repo.GoogleGoogleChrome.PasekAdresuIWyszukiwaniaInfo, new RecordItemIndex(1));
            repo.GoogleGoogleChrome.PasekAdresuIWyszukiwania.Click("434;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'o2.pl{Return}' with focus on 'GoogleGoogleChrome.PasekAdresuIWyszukiwania'.", repo.GoogleGoogleChrome.PasekAdresuIWyszukiwaniaInfo, new RecordItemIndex(2));
            repo.GoogleGoogleChrome.PasekAdresuIWyszukiwania.PressKeys("o2.pl{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'O2SerceInternetu.Poczta' at 19;9.", repo.O2SerceInternetu.PocztaInfo, new RecordItemIndex(3));
            repo.O2SerceInternetu.Poczta.Click("19;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'O2SerceInternetu.LoginForm.Username' at 121;21.", repo.O2SerceInternetu.LoginForm.UsernameInfo, new RecordItemIndex(4));
            repo.O2SerceInternetu.LoginForm.Username.Click("121;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'j{LShiftKey down}_{LShiftKey up}nowak103{LShiftKey down}@{LShiftKey up}o2.pl' with focus on 'O2SerceInternetu.LoginForm.Username'.", repo.O2SerceInternetu.LoginForm.UsernameInfo, new RecordItemIndex(5));
            repo.O2SerceInternetu.LoginForm.Username.PressKeys("j{LShiftKey down}_{LShiftKey up}nowak103{LShiftKey down}@{LShiftKey up}o2.pl");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'O2SerceInternetu.LoginForm.Password' at 76;21.", repo.O2SerceInternetu.LoginForm.PasswordInfo, new RecordItemIndex(6));
            repo.O2SerceInternetu.LoginForm.Password.Click("76;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'LkJhGfDsA123' with focus on 'O2SerceInternetu.LoginForm.Password'.", repo.O2SerceInternetu.LoginForm.PasswordInfo, new RecordItemIndex(7));
            repo.O2SerceInternetu.LoginForm.Password.PressKeys("LkJhGfDsA123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'O2SerceInternetu.LoginForm.ZalogujSię' at 54;26.", repo.O2SerceInternetu.LoginForm.ZalogujSięInfo, new RecordItemIndex(8));
            repo.O2SerceInternetu.LoginForm.ZalogujSię.Click("54;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentAto22OdebranePocztaO2.Avatar' at 11;9.", repo.WebDocumentAto22OdebranePocztaO2.AvatarInfo, new RecordItemIndex(9));
            repo.WebDocumentAto22OdebranePocztaO2.Avatar.Click("11;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentAto22OdebranePocztaO2.OlwActionsLogout' at 82;9.", repo.WebDocumentAto22OdebranePocztaO2.OlwActionsLogoutInfo, new RecordItemIndex(10));
            repo.WebDocumentAto22OdebranePocztaO2.OlwActionsLogout.Click("82;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WirtualnaPolskaWszystkoCoWażneW.Pane' at 1658;13.", repo.WirtualnaPolskaWszystkoCoWażneW.PaneInfo, new RecordItemIndex(11));
            repo.WirtualnaPolskaWszystkoCoWażneW.Pane.Click("1658;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
