///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test_1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("5d052c2c-8bbe-40bb-9113-c02407a247e9")]
    public partial class Test_1Repository : RepoGenBaseFolder
    {
        static Test_1Repository instance = new Test_1Repository();
        Test_1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Test_1RepositoryFolders.ExplorerAppFolder _explorer;
        Test_1RepositoryFolders.BezTytułuGoogleChromeAppFolder _beztytuługooglechrome;
        Test_1RepositoryFolders.GoogleGoogleChromeAppFolder _googlegooglechrome;
        Test_1RepositoryFolders.O2SerceInternetuAppFolder _o2serceinternetu;
        Test_1RepositoryFolders.WebDocumentAto22OdebranePocztaO2AppFolder _webdocumentato22odebranepocztao2;
        Test_1RepositoryFolders.WirtualnaPolskaWszystkoCoWażneWAppFolder _wirtualnapolskawszystkocoważnew;
        Test_1RepositoryFolders.WirtualnaPolskaWszystkoCoWażneW1AppFolder _wirtualnapolskawszystkocoważnew1;
        Test_1RepositoryFolders.MenedżerZadańGoogleChromeAppFolder _menedżerzadańgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the Test_1Repository element repository.
        /// </summary>
        [RepositoryFolder("5d052c2c-8bbe-40bb-9113-c02407a247e9")]
        public static Test_1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test_1Repository() 
            : base("Test_1Repository", "/", null, 0, false, "5d052c2c-8bbe-40bb-9113-c02407a247e9", ".\\RepositoryImages\\Test_1Repository5d052c2c.rximgres")
        {
            _applicationundertest = new Test_1RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new Test_1RepositoryFolders.ExplorerAppFolder(this);
            _beztytuługooglechrome = new Test_1RepositoryFolders.BezTytułuGoogleChromeAppFolder(this);
            _googlegooglechrome = new Test_1RepositoryFolders.GoogleGoogleChromeAppFolder(this);
            _o2serceinternetu = new Test_1RepositoryFolders.O2SerceInternetuAppFolder(this);
            _webdocumentato22odebranepocztao2 = new Test_1RepositoryFolders.WebDocumentAto22OdebranePocztaO2AppFolder(this);
            _wirtualnapolskawszystkocoważnew = new Test_1RepositoryFolders.WirtualnaPolskaWszystkoCoWażneWAppFolder(this);
            _wirtualnapolskawszystkocoważnew1 = new Test_1RepositoryFolders.WirtualnaPolskaWszystkoCoWażneW1AppFolder(this);
            _menedżerzadańgooglechrome = new Test_1RepositoryFolders.MenedżerZadańGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5d052c2c-8bbe-40bb-9113-c02407a247e9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("aa4d250e-b467-4ae7-83a8-5d332f39f82d")]
        public virtual Test_1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("63af912c-9712-4bee-bdeb-19134bd646f8")]
        public virtual Test_1RepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The BezTytułuGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("5a5988fb-621a-4964-a58b-d6fc4f3bb38f")]
        public virtual Test_1RepositoryFolders.BezTytułuGoogleChromeAppFolder BezTytułuGoogleChrome
        {
            get { return _beztytuługooglechrome; }
        }

        /// <summary>
        /// The GoogleGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("153fe012-b64f-4c0e-bbd5-e269994dc218")]
        public virtual Test_1RepositoryFolders.GoogleGoogleChromeAppFolder GoogleGoogleChrome
        {
            get { return _googlegooglechrome; }
        }

        /// <summary>
        /// The O2SerceInternetu folder.
        /// </summary>
        [RepositoryFolder("b66762e9-d4a4-421b-adc2-1f1d3aa37bab")]
        public virtual Test_1RepositoryFolders.O2SerceInternetuAppFolder O2SerceInternetu
        {
            get { return _o2serceinternetu; }
        }

        /// <summary>
        /// The WebDocumentAto22OdebranePocztaO2 folder.
        /// </summary>
        [RepositoryFolder("9992a5e2-82aa-4085-adb1-85b699622e96")]
        public virtual Test_1RepositoryFolders.WebDocumentAto22OdebranePocztaO2AppFolder WebDocumentAto22OdebranePocztaO2
        {
            get { return _webdocumentato22odebranepocztao2; }
        }

        /// <summary>
        /// The WirtualnaPolskaWszystkoCoWażneW folder.
        /// </summary>
        [RepositoryFolder("2b23333e-546b-42ff-918d-bdca8bbe50f6")]
        public virtual Test_1RepositoryFolders.WirtualnaPolskaWszystkoCoWażneWAppFolder WirtualnaPolskaWszystkoCoWażneW
        {
            get { return _wirtualnapolskawszystkocoważnew; }
        }

        /// <summary>
        /// The WirtualnaPolskaWszystkoCoWażneW1 folder.
        /// </summary>
        [RepositoryFolder("7a07955d-4fd9-4713-97a8-db1d2b6b0bff")]
        public virtual Test_1RepositoryFolders.WirtualnaPolskaWszystkoCoWażneW1AppFolder WirtualnaPolskaWszystkoCoWażneW1
        {
            get { return _wirtualnapolskawszystkocoważnew1; }
        }

        /// <summary>
        /// The MenedżerZadańGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("5162508c-5aad-451e-8a0a-ad3135285c09")]
        public virtual Test_1RepositoryFolders.MenedżerZadańGoogleChromeAppFolder MenedżerZadańGoogleChrome
        {
            get { return _menedżerzadańgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Test_1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("aa4d250e-b467-4ae7-83a8-5d332f39f82d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "aa4d250e-b467-4ae7-83a8-5d332f39f82d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aa4d250e-b467-4ae7-83a8-5d332f39f82d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aa4d250e-b467-4ae7-83a8-5d332f39f82d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("63af912c-9712-4bee-bdeb-19134bd646f8")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechromeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "63af912c-9712-4bee-bdeb-19134bd646f8", "")
            {
                _googlechromeInfo = new RepoItemInfo(this, "GoogleChrome", ".//toolbar[@accessiblename='Uruchomione aplikacje']/button[@accessiblename='Google Chrome']", 30000, null, "2553163b-47a2-4e97-bce0-609650fb7b0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("63af912c-9712-4bee-bdeb-19134bd646f8")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63af912c-9712-4bee-bdeb-19134bd646f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome item.
            /// </summary>
            [RepositoryItem("2553163b-47a2-4e97-bce0-609650fb7b0a")]
            public virtual Ranorex.Button GoogleChrome
            {
                get
                {
                    return _googlechromeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("2553163b-47a2-4e97-bce0-609650fb7b0a")]
            public virtual RepoItemInfo GoogleChromeInfo
            {
                get
                {
                    return _googlechromeInfo;
                }
            }
        }

        /// <summary>
        /// The BezTytułuGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("5a5988fb-621a-4964-a58b-d6fc4f3bb38f")]
        public partial class BezTytułuGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element2079172112Info;
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new BezTytułuGoogleChrome  folder.
            /// </summary>
            public BezTytułuGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BezTytułuGoogleChrome", "/form[@title>'Bez tytułu - Google Chrom']", parentFolder, 30000, null, true, "5a5988fb-621a-4964-a58b-d6fc4f3bb38f", "")
            {
                _element2079172112Info = new RepoItemInfo(this, "Element2079172112", "element[@controlid='-2079172112']", 30000, null, "2bb70965-8121-43d9-be68-7af4faa50668");
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename='Google - Google Chrome']/container/container[2]/container[1]", 30000, null, "459d9ebc-bc7e-4707-915b-1d5b255369ec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5a5988fb-621a-4964-a58b-d6fc4f3bb38f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5a5988fb-621a-4964-a58b-d6fc4f3bb38f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element2079172112 item.
            /// </summary>
            [RepositoryItem("2bb70965-8121-43d9-be68-7af4faa50668")]
            public virtual Ranorex.Unknown Element2079172112
            {
                get
                {
                    return _element2079172112Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element2079172112 item info.
            /// </summary>
            [RepositoryItemInfo("2bb70965-8121-43d9-be68-7af4faa50668")]
            public virtual RepoItemInfo Element2079172112Info
            {
                get
                {
                    return _element2079172112Info;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("459d9ebc-bc7e-4707-915b-1d5b255369ec")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("459d9ebc-bc7e-4707-915b-1d5b255369ec")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

        /// <summary>
        /// The GoogleGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("153fe012-b64f-4c0e-bbd5-e269994dc218")]
        public partial class GoogleGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pasekadresuiwyszukiwaniaInfo;

            /// <summary>
            /// Creates a new GoogleGoogleChrome  folder.
            /// </summary>
            public GoogleGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GoogleGoogleChrome", "/form[@title='Google - Google Chrome']", parentFolder, 30000, null, true, "153fe012-b64f-4c0e-bbd5-e269994dc218", "")
            {
                _pasekadresuiwyszukiwaniaInfo = new RepoItemInfo(this, "PasekAdresuIWyszukiwania", "container[@accessiblename='Google - Google Chrome']/container[@accessiblename='Google Chrome']//container[@accessiblerole='Grouping']/text[@accessiblename>'Pasek adresu i wyszukiwan']", 30000, null, "387c33d0-bd82-40f5-96c5-7be671ea5bc5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("153fe012-b64f-4c0e-bbd5-e269994dc218")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("153fe012-b64f-4c0e-bbd5-e269994dc218")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PasekAdresuIWyszukiwania item.
            /// </summary>
            [RepositoryItem("387c33d0-bd82-40f5-96c5-7be671ea5bc5")]
            public virtual Ranorex.Text PasekAdresuIWyszukiwania
            {
                get
                {
                    return _pasekadresuiwyszukiwaniaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PasekAdresuIWyszukiwania item info.
            /// </summary>
            [RepositoryItemInfo("387c33d0-bd82-40f5-96c5-7be671ea5bc5")]
            public virtual RepoItemInfo PasekAdresuIWyszukiwaniaInfo
            {
                get
                {
                    return _pasekadresuiwyszukiwaniaInfo;
                }
            }
        }

        /// <summary>
        /// The O2SerceInternetuAppFolder folder.
        /// </summary>
        [RepositoryFolder("b66762e9-d4a4-421b-adc2-1f1d3aa37bab")]
        public partial class O2SerceInternetuAppFolder : RepoGenBaseFolder
        {
            Test_1RepositoryFolders.LoginFormFolder _loginform;
            RepoItemInfo _pocztaInfo;

            /// <summary>
            /// Creates a new O2SerceInternetu  folder.
            /// </summary>
            public O2SerceInternetuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("O2SerceInternetu", "/dom[@domain='www.o2.pl']", parentFolder, 30000, null, false, "b66762e9-d4a4-421b-adc2-1f1d3aa37bab", "")
            {
                _loginform = new Test_1RepositoryFolders.LoginFormFolder(this);
                _pocztaInfo = new RepoItemInfo(this, "Poczta", ".//ul[#'header-menu']//span[@innertext='Poczta']", 30000, null, "12a8f5c5-7ee1-4c8d-8d82-10da3d107235");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b66762e9-d4a4-421b-adc2-1f1d3aa37bab")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b66762e9-d4a4-421b-adc2-1f1d3aa37bab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Poczta item.
            /// </summary>
            [RepositoryItem("12a8f5c5-7ee1-4c8d-8d82-10da3d107235")]
            public virtual Ranorex.SpanTag Poczta
            {
                get
                {
                    return _pocztaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Poczta item info.
            /// </summary>
            [RepositoryItemInfo("12a8f5c5-7ee1-4c8d-8d82-10da3d107235")]
            public virtual RepoItemInfo PocztaInfo
            {
                get
                {
                    return _pocztaInfo;
                }
            }

            /// <summary>
            /// The LoginForm folder.
            /// </summary>
            [RepositoryFolder("8fcb3f70-56d0-4d00-95ca-ac5a1ee99109")]
            public virtual Test_1RepositoryFolders.LoginFormFolder LoginForm
            {
                get { return _loginform; }
            }
        }

        /// <summary>
        /// The LoginFormFolder folder.
        /// </summary>
        [RepositoryFolder("8fcb3f70-56d0-4d00-95ca-ac5a1ee99109")]
        public partial class LoginFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _zalogujsięInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _usernameInfo;

            /// <summary>
            /// Creates a new LoginForm  folder.
            /// </summary>
            public LoginFormFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginForm", ".//form[#'loginForm']", parentFolder, 30000, null, false, "8fcb3f70-56d0-4d00-95ca-ac5a1ee99109", "")
            {
                _zalogujsięInfo = new RepoItemInfo(this, "ZalogujSię", "?/?/button[@innertext='Zaloguj się']", 30000, null, "41a15717-7997-4d77-95d4-81de95e6ed8c");
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/input[@name='password']", 30000, null, "de4fc47e-85b6-4bc2-9dc6-58873f748510");
                _usernameInfo = new RepoItemInfo(this, "Username", "?/?/input[@name='username']", 30000, null, "6d29e18b-d0c9-4c84-b18e-633ca430cdf0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8fcb3f70-56d0-4d00-95ca-ac5a1ee99109")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8fcb3f70-56d0-4d00-95ca-ac5a1ee99109")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ZalogujSię item.
            /// </summary>
            [RepositoryItem("41a15717-7997-4d77-95d4-81de95e6ed8c")]
            public virtual Ranorex.ButtonTag ZalogujSię
            {
                get
                {
                    return _zalogujsięInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ZalogujSię item info.
            /// </summary>
            [RepositoryItemInfo("41a15717-7997-4d77-95d4-81de95e6ed8c")]
            public virtual RepoItemInfo ZalogujSięInfo
            {
                get
                {
                    return _zalogujsięInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("de4fc47e-85b6-4bc2-9dc6-58873f748510")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("de4fc47e-85b6-4bc2-9dc6-58873f748510")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("6d29e18b-d0c9-4c84-b18e-633ca430cdf0")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("6d29e18b-d0c9-4c84-b18e-633ca430cdf0")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }
        }

        /// <summary>
        /// The WebDocumentAto22OdebranePocztaO2AppFolder folder.
        /// </summary>
        [RepositoryFolder("9992a5e2-82aa-4085-adb1-85b699622e96")]
        public partial class WebDocumentAto22OdebranePocztaO2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _olwactionslogoutInfo;
            RepoItemInfo _webelementsvgInfo;
            RepoItemInfo _avatarInfo;

            /// <summary>
            /// Creates a new WebDocumentAto22OdebranePocztaO2  folder.
            /// </summary>
            public WebDocumentAto22OdebranePocztaO2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("WebDocumentAto22OdebranePocztaO2", "/dom[@domain='poczta.o2.pl']", parentFolder, 30000, null, false, "9992a5e2-82aa-4085-adb1-85b699622e96", "")
            {
                _olwactionslogoutInfo = new RepoItemInfo(this, "OlwActionsLogout", ".//a[#'olw-actions-logout']", 30000, null, "4ceb4970-12ea-444a-934e-585c348c5ff6");
                _webelementsvgInfo = new RepoItemInfo(this, "WebElementSvg", ".//div[#'main']/tag/div/tag[@tagname='nh-top-bar']/div/div[1]/div[4]/div/div/div[3]/tag[@tagname='svg']", 30000, null, "6c27ab6a-6d5e-4e55-84a7-b0dcd3b38188");
                _avatarInfo = new RepoItemInfo(this, "Avatar", ".//button[#'olw-db-button']/?/?/img[@alt='avatar']", 30000, null, "bbd4147a-6752-4b8b-836f-3a5cdd5a4671");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9992a5e2-82aa-4085-adb1-85b699622e96")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9992a5e2-82aa-4085-adb1-85b699622e96")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OlwActionsLogout item.
            /// </summary>
            [RepositoryItem("4ceb4970-12ea-444a-934e-585c348c5ff6")]
            public virtual Ranorex.ATag OlwActionsLogout
            {
                get
                {
                    return _olwactionslogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OlwActionsLogout item info.
            /// </summary>
            [RepositoryItemInfo("4ceb4970-12ea-444a-934e-585c348c5ff6")]
            public virtual RepoItemInfo OlwActionsLogoutInfo
            {
                get
                {
                    return _olwactionslogoutInfo;
                }
            }

            /// <summary>
            /// The WebElementSvg item.
            /// </summary>
            [RepositoryItem("6c27ab6a-6d5e-4e55-84a7-b0dcd3b38188")]
            public virtual Ranorex.WebElement WebElementSvg
            {
                get
                {
                    return _webelementsvgInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The WebElementSvg item info.
            /// </summary>
            [RepositoryItemInfo("6c27ab6a-6d5e-4e55-84a7-b0dcd3b38188")]
            public virtual RepoItemInfo WebElementSvgInfo
            {
                get
                {
                    return _webelementsvgInfo;
                }
            }

            /// <summary>
            /// The Avatar item.
            /// </summary>
            [RepositoryItem("bbd4147a-6752-4b8b-836f-3a5cdd5a4671")]
            public virtual Ranorex.ImgTag Avatar
            {
                get
                {
                    return _avatarInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Avatar item info.
            /// </summary>
            [RepositoryItemInfo("bbd4147a-6752-4b8b-836f-3a5cdd5a4671")]
            public virtual RepoItemInfo AvatarInfo
            {
                get
                {
                    return _avatarInfo;
                }
            }
        }

        /// <summary>
        /// The WirtualnaPolskaWszystkoCoWażneWAppFolder folder.
        /// </summary>
        [RepositoryFolder("2b23333e-546b-42ff-918d-bdca8bbe50f6")]
        public partial class WirtualnaPolskaWszystkoCoWażneWAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new WirtualnaPolskaWszystkoCoWażneW  folder.
            /// </summary>
            public WirtualnaPolskaWszystkoCoWażneWAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WirtualnaPolskaWszystkoCoWażneW", "/form[@title>'Wirtualna Polska - Wszystko']", parentFolder, 30000, null, true, "2b23333e-546b-42ff-918d-bdca8bbe50f6", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'Wirtualna Polska - Wszystko']/container/container[2]/container[1]", 30000, null, "e6d65f52-0a33-43ee-90cd-21fcc170d1e6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b23333e-546b-42ff-918d-bdca8bbe50f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b23333e-546b-42ff-918d-bdca8bbe50f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("e6d65f52-0a33-43ee-90cd-21fcc170d1e6")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("e6d65f52-0a33-43ee-90cd-21fcc170d1e6")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

        /// <summary>
        /// The WirtualnaPolskaWszystkoCoWażneW1AppFolder folder.
        /// </summary>
        [RepositoryFolder("7a07955d-4fd9-4713-97a8-db1d2b6b0bff")]
        public partial class WirtualnaPolskaWszystkoCoWażneW1AppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new WirtualnaPolskaWszystkoCoWażneW1  folder.
            /// </summary>
            public WirtualnaPolskaWszystkoCoWażneW1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("WirtualnaPolskaWszystkoCoWażneW1", "/dom[@domain='www.wp.pl']", parentFolder, 30000, null, false, "7a07955d-4fd9-4713-97a8-db1d2b6b0bff", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7a07955d-4fd9-4713-97a8-db1d2b6b0bff")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7a07955d-4fd9-4713-97a8-db1d2b6b0bff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The MenedżerZadańGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("5162508c-5aad-451e-8a0a-ad3135285c09")]
        public partial class MenedżerZadańGoogleChromeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new MenedżerZadańGoogleChrome  folder.
            /// </summary>
            public MenedżerZadańGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MenedżerZadańGoogleChrome", "/form[@title>'Menedżer zadań – Google C']", parentFolder, 30000, null, true, "5162508c-5aad-451e-8a0a-ad3135285c09", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5162508c-5aad-451e-8a0a-ad3135285c09")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5162508c-5aad-451e-8a0a-ad3135285c09")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
